spring:
  application:
    name: Hj212-Distribute
  redis:
    # 测试地址
    host: 39.104.54.184
    # 发布地址
    #host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 测试数据库索引
    database: 6
    # 发布数据库索引
    #database: 3
    # 密码
    password: Hfzn_2022_R